.TH "gnuplotio::BinfmtSender< boost::uint16_t >" 3 "Fri Nov 22 2019" "Version 7" "GMock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::BinfmtSender< boost::uint16_t > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsend\fP (std::ostream &stream)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct gnuplotio::BinfmtSender< boost::uint16_t >"

.PP
Definition at line 473 of file gnuplot\-iostream\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "static void \fBgnuplotio::BinfmtSender\fP< boost::uint16_t >::send (std::ostream & stream)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 473 of file gnuplot\-iostream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GMock from the source code\&.
