.TH "gnuplotio::ArrayTraits< T[N]>" 3 "Fri Nov 22 2019" "Version 7" "GMock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::ArrayTraits< T[N]> \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.PP
Inherits \fBgnuplotio::ArrayTraitsDefaults< T >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBIteratorRange\fP< const T *, T > \fBrange_type\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBrange_type\fP \fBget_range\fP (const T(&arg)[N])"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T, size_t N>
.br
class gnuplotio::ArrayTraits< T[N]>"

.PP
Definition at line 913 of file gnuplot\-iostream\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T , size_t N> typedef \fBIteratorRange\fP<const T*, T> \fBgnuplotio::ArrayTraits\fP< T[N]>::\fBrange_type\fP"

.PP
Definition at line 915 of file gnuplot\-iostream\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T , size_t N> static \fBrange_type\fP \fBgnuplotio::ArrayTraits\fP< T[N]>::get_range (const T(&) arg[N])\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 917 of file gnuplot\-iostream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GMock from the source code\&.
