.TH "gnuplotio::ArrayTraitsDefaults< V >" 3 "Fri Nov 22 2019" "Version 7" "GMock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::ArrayTraitsDefaults< V > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef V \fBvalue_type\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBis_container\fP = true"
.br
.ti -1c
.RI "static const bool \fBallow_auto_unwrap\fP = true"
.br
.ti -1c
.RI "static const size_t \fBdepth\fP = \fBArrayTraits\fP<V>::depth + 1"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename V>
.br
class gnuplotio::ArrayTraitsDefaults< V >"

.PP
Definition at line 833 of file gnuplot\-iostream\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename V> typedef V \fBgnuplotio::ArrayTraitsDefaults\fP< V >::\fBvalue_type\fP"

.PP
Definition at line 835 of file gnuplot\-iostream\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename V> const bool \fBgnuplotio::ArrayTraitsDefaults\fP< V >::allow_auto_unwrap = true\fC [static]\fP"

.PP
Definition at line 838 of file gnuplot\-iostream\&.h\&.
.SS "template<typename V> const size_t \fBgnuplotio::ArrayTraitsDefaults\fP< V >::depth = \fBArrayTraits\fP<V>::depth + 1\fC [static]\fP"

.PP
Definition at line 839 of file gnuplot\-iostream\&.h\&.
.SS "template<typename V> const bool \fBgnuplotio::ArrayTraitsDefaults\fP< V >::is_container = true\fC [static]\fP"

.PP
Definition at line 837 of file gnuplot\-iostream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GMock from the source code\&.
