.TH "gnuplotio::TextSender< char >" 3 "Fri Nov 22 2019" "Version 7" "GMock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::TextSender< char > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.PP
Inherits \fBgnuplotio::CastIntTextSender< char >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct gnuplotio::TextSender< char >"

.PP
Definition at line 499 of file gnuplot\-iostream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GMock from the source code\&.
