.TH "gnuplotio::TextSender< std::complex< T > >" 3 "Fri Nov 22 2019" "Version 7" "GMock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::TextSender< std::complex< T > > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsend\fP (std::ostream &stream, const std::complex< T > &v)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct gnuplotio::TextSender< std::complex< T > >"

.PP
Definition at line 548 of file gnuplot\-iostream\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > static void \fBgnuplotio::TextSender\fP< std::complex< T > >::send (std::ostream & stream, const std::complex< T > & v)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 549 of file gnuplot\-iostream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GMock from the source code\&.
