.TH "gnuplotio::ArrayTraits< T, Enable >" 3 "Fri Nov 22 2019" "Version 7" "GMock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::ArrayTraits< T, Enable > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBError_WasNotContainer\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBError_WasNotContainer\fP \fBrange_type\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBrange_type\fP \fBget_range\fP (const T &)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBis_container\fP = false"
.br
.ti -1c
.RI "static const bool \fBallow_auto_unwrap\fP = false"
.br
.ti -1c
.RI "static const size_t \fBdepth\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename Enable = void>
.br
class gnuplotio::ArrayTraits< T, Enable >"

.PP
Definition at line 807 of file gnuplot\-iostream\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T, typename Enable = void> typedef \fBError_WasNotContainer\fP \fBgnuplotio::ArrayTraits\fP< T, Enable >::\fBrange_type\fP"

.PP
Definition at line 812 of file gnuplot\-iostream\&.h\&.
.SS "template<typename T, typename Enable = void> typedef \fBError_WasNotContainer\fP \fBgnuplotio::ArrayTraits\fP< T, Enable >::\fBvalue_type\fP"

.PP
Definition at line 810 of file gnuplot\-iostream\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T, typename Enable = void> static \fBrange_type\fP \fBgnuplotio::ArrayTraits\fP< T, Enable >::get_range (const T &)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 824 of file gnuplot\-iostream\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T, typename Enable = void> const bool \fBgnuplotio::ArrayTraits\fP< T, Enable >::allow_auto_unwrap = false\fC [static]\fP"

.PP
Definition at line 819 of file gnuplot\-iostream\&.h\&.
.SS "template<typename T, typename Enable = void> const size_t \fBgnuplotio::ArrayTraits\fP< T, Enable >::depth = 0\fC [static]\fP"

.PP
Definition at line 821 of file gnuplot\-iostream\&.h\&.
.SS "template<typename T, typename Enable = void> const bool \fBgnuplotio::ArrayTraits\fP< T, Enable >::is_container = false\fC [static]\fP"

.PP
Definition at line 814 of file gnuplot\-iostream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GMock from the source code\&.
