.TH "gnuplotio::GnuplotFeedback" 3 "Fri Nov 22 2019" "Version 7" "GMock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::GnuplotFeedback \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGnuplotFeedback\fP ()"
.br
.ti -1c
.RI "virtual \fB~GnuplotFeedback\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBfilename\fP () const =0"
.br
.ti -1c
.RI "virtual FILE * \fBhandle\fP () const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 290 of file gnuplot\-iostream\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gnuplotio::GnuplotFeedback::GnuplotFeedback ()\fC [inline]\fP"

.PP
Definition at line 292 of file gnuplot\-iostream\&.h\&.
.SS "virtual gnuplotio::GnuplotFeedback::~GnuplotFeedback ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 293 of file gnuplot\-iostream\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual std::string gnuplotio::GnuplotFeedback::filename () const\fC [pure virtual]\fP"

.SS "virtual FILE* gnuplotio::GnuplotFeedback::handle () const\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GMock from the source code\&.
