.TH "gnuplotio::BinfmtSender< T, Enable >" 3 "Fri Nov 22 2019" "Version 7" "GMock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::BinfmtSender< T, Enable > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGNUPLOT_STATIC_ASSERT_MSG\fP ((sizeof(T)==0),'BinfmtSender class not specialized for this type')"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsend\fP (std::ostream &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename Enable = void>
.br
struct gnuplotio::BinfmtSender< T, Enable >"

.PP
Definition at line 459 of file gnuplot\-iostream\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T, typename Enable = void> \fBgnuplotio::BinfmtSender\fP< T, Enable >::GNUPLOT_STATIC_ASSERT_MSG ((sizeof(T)==0), 'BinfmtSender< T, Enable > class not specialized for this type')"

.SS "template<typename T, typename Enable = void> static void \fBgnuplotio::BinfmtSender\fP< T, Enable >::send (std::ostream &)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GMock from the source code\&.
