.TH "gnuplotio::is_boost_tuple_nulltype< boost::tuples::null_type >" 3 "Fri Nov 22 2019" "Version 7" "GMock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::is_boost_tuple_nulltype< boost::tuples::null_type > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef boost::mpl::bool_< \fBvalue\fP > \fBtype\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct gnuplotio::is_boost_tuple_nulltype< boost::tuples::null_type >"

.PP
Definition at line 204 of file gnuplot\-iostream\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef boost::mpl::bool_<\fBvalue\fP> \fBgnuplotio::is_boost_tuple_nulltype\fP< boost::tuples::null_type >::\fBtype\fP"

.PP
Definition at line 206 of file gnuplot\-iostream\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "const bool \fBgnuplotio::is_boost_tuple_nulltype\fP< boost::tuples::null_type >::value = true\fC [static]\fP"

.PP
Definition at line 205 of file gnuplot\-iostream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GMock from the source code\&.
