.TH "gnuplotio::plotting_empty_container" 3 "Fri Nov 22 2019" "Version 7" "GMock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::plotting_empty_container \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.PP
Inherits length_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBplotting_empty_container\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1180 of file gnuplot\-iostream\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gnuplotio::plotting_empty_container::plotting_empty_container ()\fC [inline]\fP"

.PP
Definition at line 1182 of file gnuplot\-iostream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GMock from the source code\&.
