.TH "gnuplotio::ArrayTraits< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, is_boost_tuple_nulltype< typename T::tail_type > > >::type >" 3 "Fri Nov 22 2019" "Version 7" "GMock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::ArrayTraits< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, is_boost_tuple_nulltype< typename T::tail_type > > >::type > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.PP
Inherits \fBgnuplotio::ArrayTraits< T::head_type >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBparent::range_type\fP \fBget_range\fP (const T &arg)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class gnuplotio::ArrayTraits< T, typename boost::enable_if< boost::mpl::and_< is_boost_tuple< T >, is_boost_tuple_nulltype< typename T::tail_type > > >::type >"

.PP
Definition at line 1022 of file gnuplot\-iostream\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > static \fBparent::range_type\fP \fBgnuplotio::ArrayTraits\fP< T, typename boost::enable_if< boost::mpl::and_< \fBis_boost_tuple\fP< T >, \fBis_boost_tuple_nulltype\fP< typename T::tail_type > > >::type >::get_range (const T & arg)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 1037 of file gnuplot\-iostream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GMock from the source code\&.
