.TH "gnuplotio::is_boost_tuple_nulltype< T >" 3 "Fri Nov 22 2019" "Version 7" "GMock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::is_boost_tuple_nulltype< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef boost::mpl::bool_< \fBvalue\fP > \fBtype\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct gnuplotio::is_boost_tuple_nulltype< T >"

.PP
Definition at line 198 of file gnuplot\-iostream\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef boost::mpl::bool_<\fBvalue\fP> \fBgnuplotio::is_boost_tuple_nulltype\fP< T >::\fBtype\fP"

.PP
Definition at line 200 of file gnuplot\-iostream\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T > const bool \fBgnuplotio::is_boost_tuple_nulltype\fP< T >::value = false\fC [static]\fP"

.PP
Definition at line 199 of file gnuplot\-iostream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GMock from the source code\&.
