.TH "gnuplotio::Mode2DUnwrap" 3 "Fri Nov 22 2019" "Version 7" "GMock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gnuplotio::Mode2DUnwrap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gnuplot\-iostream\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBclass_name\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1210 of file gnuplot\-iostream\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "static std::string gnuplotio::Mode2DUnwrap::class_name ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 1210 of file gnuplot\-iostream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GMock from the source code\&.
