.TH "test/mockNavigation.cpp" 3 "Fri Nov 22 2019" "Version 7" "GMock" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/mockNavigation.cpp \- Mid Term Project\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include <gmock/gmock\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'iostream'\fP
.br
\fC#include 'Navigation\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMockNavigation\fP"
.br
.RI "\fIMock Class \fBNavigation\fP To implement google mock\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBMockNavigation\fP, checkKp)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBMockNavigation\fP, checkKi)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBMockNavigation\fP, checkKd)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBMockNavigation\fP, checkPID)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBMockNavigation\fP, checkNavigation)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Mid Term Project\&. 


.PP
\fBCopyright:\fP
.RS 4
MIT License, Copyright © 2019 Raj Shinde
.RE
.PP
\fBAuthor:\fP
.RS 4
Prasheel Renkuntla 
.RE
.PP
\fBDate:\fP
.RS 4
11/22/2019 
.RE
.PP
\fBVersion:\fP
.RS 4
7\&.0 
.RE
.PP
.SH "all files in module with gmock"
.PP

.PP
Definition in file \fBmockNavigation\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "TEST (\fBMockNavigation\fP, checkKp)"

.PP
Definition at line 98 of file mockNavigation\&.cpp\&.
.SS "TEST (\fBMockNavigation\fP, checkKi)"

.PP
Definition at line 112 of file mockNavigation\&.cpp\&.
.SS "TEST (\fBMockNavigation\fP, checkKd)"

.PP
Definition at line 126 of file mockNavigation\&.cpp\&.
.SS "TEST (\fBMockNavigation\fP, checkPID)"

.PP
Definition at line 141 of file mockNavigation\&.cpp\&.
.SS "TEST (\fBMockNavigation\fP, checkNavigation)"

.PP
Definition at line 153 of file mockNavigation\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GMock from the source code\&.
